stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

image: python:latest # docker image used for the job

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache: 
  paths:
    - .cache/pip # directory that should be cached between jobs

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

build:
  script:
    - flask --app app run
  artifacts:
    paths:
      - .cache/pip

test:    # It only starts when the job in the build stage completes successfully.
  script:
    - pytest

deploy:  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  # image: registry.gitlab.unige.ch/courses1/pt1324/g14/flask:superioir
  script:
    - podman --version
