stages:          # stageless pipeline
  - build
  - test
  - deploy

image: python:latest # docker image used for the job

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache: 
  paths:
    - .cache/pip # directory that should be cached between jobs

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

build:
  stage: build
  script:
    - pip install --no-cache-dir -r ./checkpoint2/flaskr/requirements.txt # install requirements
    - pip install pytest
  artifacts:
    paths:
      - .cache/pip

test:    # It only starts when the job in the build stage completes successfully.
  stage: test
  script:
    - cd checkpoint2/flaskr/
    - pytest # run tests using pytest

deploy:  # It only runs when *both* jobs in the test stage complete successfully.
  stage: deploy
  environment: production
  # image: registry.gitlab.unige.ch/courses1/pt1324/g14/flask:superioir
  script:
    - podman --version

include:
  - template: Jobs/SAST.gitlab-ci.yml # creates SAST jobs in your CI/CD pipeline and scans your project’s source code for possible vulnerabilities
