@startuml
skinparam linetype ortho
class universe{
	Name      name
    	Text      description
}

class title{
    	Date        date
    	Text      Title
    	Time        lenght
}

class award{
	Text award_name	
	Text Title
}

class category{
	Text category
	Text Title
}

class people{
    	Name      name
    	Date        birth_year
    	Date        death_year
}

class watchlist{
}

class user{
    	Name      pseudo
    	Date        inscription_date
}

class review{
    	Int         rating
    	Date        creation
    	Text      body
}

class role{
    	Name      character
}

class job{
	Text job
}

universe "0..1" -- "2..*" title
title "0..*" -- "1..*" people
title "0..*" -- "1" review
title "1" -- "0..*" award
title "1" -- "1..*" category
review "0..*" -- "1" user
user "1" -- "1" watchlist
watchlist "0..*" -- "0..*" title
role "1" -- "0..*" job : includes

(title, people) .. role

@enduml
