FROM python:3.12-alpine

# Set the working directory within the container
WORKDIR /DBMi-flask

# Copy the necessary files and directories into the container
COPY ./algo.py ./db.py ./app.py ./auth.py ./routes.py /DBMi-flask
COPY ./requirements.txt ./api_routes.py ./sessionkey.txt ./tests/* ./static/* /DBMi-flask

RUN apk update \
    && apk add --no-cache build-base \
    && pip3 install --upgrade pip \
    && pip install -r requirements.txt

ENV FLASK_APP=app.py

# Expose port 5000 for the Flask application
EXPOSE 5014

# Define the command to run the Flask application using Gunicorn
CMD python -m flask run --port 5014
