@startuml
left to right direction
[client]
package "Flask application" as FA{
	[Routes] as R
	[API routes] as AR
	[Authentication] as A
	[Database] as D
}

database "MySQL database" as md #LightBlue{
}

D ..|> AR
D ..|> A
[client] ..> R : standard request
R ..> AR : standard request
AR ..> md : standard request
md ..> AR : standard response
AR ..> R : standard response
R ..> [client] : standard response

[client] ..> A : Authentication request
A ..> md : Authentication request
md ..> A : Authentication response
A ..> [client] : Authentication response


@enduml
