@startuml
[client]
component "Flask application" as FA{
	portin p1
	portin p2
	portout p11
	portout p21
}

component "RDBMS"{
	database "MySQL database" as md #LightBlue{
	}
}

[client] ..> p1 : standard request
p11 ..> md : standard request
md ..> p2 : standard response
p21 ..> [client] : standard response

[client] ..> p1 : Authentication request
p11 ..> md : Authentication request
md ..> p2 : Authentication response
p21 ..> [client] : Authentication response


@enduml
